name: Update ReadME

on: push

jobsNo such file or directory:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -la
      - run: python3 build.py
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "auto updated readme"

